### ISSUE TITLE
PHP Warning: invalid path in zc_plugins/EasyPopulateV4/v4.0.39.ZC/Installer/ScriptedInstaller.php on line 68.

### ISSUE THREAD

**Issue by torvista** [mc12345678/EasyPopulate-4.0#71]
Using latest branch.
Since this error comes from three possible clauses/causes, it's not easy to determine the issue as the code stands.

**Comment by mc12345678** [comment]
I have no idea how to respond to this, for so many reasons. I expect it is posted with positive intention; however, I do not know what is sought, what the issue is or what has been impacted.

It reads as if to say: if an issue is logged here, then it may be difficult to determine the cause. If that is all that is being reported, then I would say mission accomplished at identifying the goal of making that particular reporting difficult to determine the cause. First of all, I don't believe it should happen; however, it is a possibility depending on the path that this ZC plugin coding takes.

It could be that the logging is unnecessary; however, in absence of more information it appears that this is a condition that is being found "likely" but undesirable or what.

It's also not easy to determine if this is a "what if triggered" type question or a report of that the issue has been triggered. I say this because I would have expected in reporting this situation that more information would have been provided... What version of Zen Cart, what action was done to prompt the issue, what was on the uri (omitting the admin foldername) as this last piece of data supports identifying reason for generating the log. 

In a way, there seemed to be something about the verification that suggested should not report too much fine detail about this aspect. It seems like it is a do or not do condition. Yes, there are multiple `ors` but, they are to minimize the related php logs if the condition is undesirable. I basically want to use a "properly" originated path; however, I do not see the plugin and file related code providing the necessary results.

**Comment by torvista** [comment]
Windows, php 8.3.4, latest branch on ZC200.
When installed via the Plugin Manager, I got this error.
I assume a branch is expected to be working/not with known bugs.
So, the point I was making is that the error message is triggered by three possible clauses, thereby making it impossible to investigate without modifying the code to get a specific message.
I hardly ever use EP and don't need this error to be fixed, I was just pointing out an issue with the branch as it stands which does not seem to be documented, but can be fixed at leisure.

**Comment by mc12345678** [comment]
Agree, branch should be functional and was under 1.5.8. As identified elsewhere in the issues, there have been some version 2.0.0 issues. Thank you for pointing them out and assisting. As discussed elsewhere in the zencart github I hadn't attempted any development against version 2.0.0. It was released a couple of days ago and I am now making way through it. 

As to this issue, could you please identify what was on the uri after the admin folder name when this issue was identified? That may identify a compatibility difference specific to version 2.0.0. If data there is a expected then it's the post information that needs to be addressed.

**Comment by torvista** [comment]
It **does** install, it just generates a debug (strict reporting).
The urls of each step.

> https://www.site.local/admin/index.php?cmd=plugin_manager&page=1&colKey=EasyPopulateV4
> https://www.site.local/admin/index.php?cmd=plugin_manager&page=1&colKey=EasyPopulateV4&action=install
> https://www.site.local/admin/index.php?cmd=plugin_manager&page=1&colKey=EasyPopulateV4

> 10-Apr-2024 15:05:19:000000 Europe/Madrid] Request URI: /ADMIN/index.php?cmd=plugin_manager&page=1&colKey=EasyPopulateV4&action=doInstall
> IP address: 127.0.0.1, Language id 1
> #0 [internal function]: zen_debug_error_handler()
> #1 zc_plugins/EasyPopulateV4/v4.0.39.ZC/Installer/ScriptedInstaller.php(68): trigger_error()
> #2 includes/classes/PluginSupport/ScriptedInstaller.php(32): ScriptedInstaller->executeInstall()
> #3 includes/classes/PluginSupport/Installer.php(91): Zencart/PluginSupport/ScriptedInstaller->doInstall()
> #4 includes/classes/PluginSupport/Installer.php(42): Zencart/PluginSupport/Installer->executeScriptedInstaller()
> #5 includes/classes/PluginSupport/BasePluginInstaller.php(45): Zencart/PluginSupport/Installer->executeInstallers()
> #6 includes/classes/ViewBuilders/PluginManagerController.php(132): Zencart/PluginSupport/BasePluginInstaller->processInstall()
> #7 includes/classes/ViewBuilders/BaseController.php(37): Zencart/ViewBuilders/PluginManagerController->processActionDoInstall()
> #8 ADMIN/plugin_manager.php(94): Zencart/ViewBuilders/BaseController->processRequest()
> #9 ADMIN/index.php(11): require('D://OneDrive//Bus...')
> --> PHP Warning: invalid path in zc_plugins/EasyPopulateV4/v4.0.39.ZC/Installer/ScriptedInstaller.php on line 68.
